[tool.poetry]
name = "Legog-bot-discord"
version = "1.0.0"
description = ""
authors = ["Gabriel Gustavo <gabriel.gustavo.s@hotmail.com>"]

[tool.poetry.dependencies]
python= "3.8"
python-dotenv= "0.14.0"
requests= "2.24.0"
discord= "1.4.1"