[tool.poetry]
name = "Legog-bot-discord"
version = "1.0.0"
description = ""
authors = ["Gabriel Gustavo <gabriel.gustavo.s@hotmail.com>"]

[tool.poetry.dependencies]
python= "^3.5"
dotenv-python= "^0.0.0"
discord= "^1.0.0"